--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE FORCE VIEW VENTASPERIODOTIEMPO
AS
	--verificar que la fecha de inicio sea menor que la fecha de fin
    SELECT SUM(NUMERO_VENTAS) NUMERO_VENTAS, SUM(INGRESOS) INGRESOS FROM
    (
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@hmo
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@quro
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@tg
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
    ) 
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE FORCE VIEW VENTASPERIODOTIEMPO
AS
	--verificar que la fecha de inicio sea menor que la fecha de fin
    SELECT SUM(NUMERO_VENTAS) NUMERO_VENTAS, SUM(INGRESOS) INGRESOS FROM
    (
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@mty
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@quro
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@tg
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
    ) 

--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE FORCE VIEW VENTASPERIODOTIEMPO
AS
	--verificar que la fecha de inicio sea menor que la fecha de fin
    SELECT SUM(NUMERO_VENTAS) NUMERO_VENTAS, SUM(INGRESOS) INGRESOS FROM
    (
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@mty
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@hmo
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@tg
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
    ) 

--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE FORCE VIEW VENTASPERIODOTIEMPO
AS
	--verificar que la fecha de inicio sea menor que la fecha de fin
    SELECT SUM(NUMERO_VENTAS) NUMERO_VENTAS, SUM(INGRESOS) INGRESOS FROM
    (
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@mty
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@hmo
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA@quro
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
        UNION
        SELECT COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
        FROM VENTA
        WHERE FECHA BETWEEN SYSDATE - 60 AND SYSDATE
    ) 

--------------------------------------------------------------------------------