--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE PROCEDURE VENTASPERIODOTIEMPO
(
	P_FECHAINICIO IN DATETIME,
	P_FECHAFIN IN DATETIME,
) 
AS
BEGIN
	--verificar que la fecha de inicio sea menor que la fecha de fin
	IF P_FECHAINICIO > P_FECHAFIN THEN
		raise_application_error(-15000,'{La fecha de inicio no puede ser mayor que la fecha de fin.}');
	ELSE
	SELECT COUNT(PRECIO) 'NUMERO_VENTAS', SUM(PRECIO) 'INGRESOS' FROM ventas_totales,
	(
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@hmo
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@quro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) ventas_totales
	ENDIF;
END VENTASPERIODOTIEMPO;
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE PROCEDURE VENTASPERIODOTIEMPO
(
	P_FECHAINICIO IN DATETIME,
	P_FECHAFIN IN DATETIME,
) 
AS
BEGIN
	--verificar que la fecha de inicio sea menor que la fecha de fin
	IF P_FECHAINICIO > P_FECHAFIN THEN
		raise_application_error(-15000,'{La fecha de inicio no puede ser mayor que la fecha de fin.}');
	ELSE
	SELECT COUNT(PRECIO) 'NUMERO_VENTAS', SUM(PRECIO) 'INGRESOS' FROM ventas_totales,
	(
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@quro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) ventas_totales
	ENDIF;
END VENTASPERIODOTIEMPO;
--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE PROCEDURE VENTASPERIODOTIEMPO
(
	P_FECHAINICIO IN DATETIME,
	P_FECHAFIN IN DATETIME,
) 
AS
BEGIN
	--verificar que la fecha de inicio sea menor que la fecha de fin
	IF P_FECHAINICIO > P_FECHAFIN THEN
		raise_application_error(-15000,'{La fecha de inicio no puede ser mayor que la fecha de fin.}');
	ELSE
	SELECT COUNT(PRECIO) 'NUMERO_VENTAS', SUM(PRECIO) 'INGRESOS' FROM ventas_totales,
	(
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@quro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) ventas_totales
	ENDIF;
END VENTASPERIODOTIEMPO;
--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE PROCEDURE VENTASPERIODOTIEMPO
(
	P_FECHAINICIO IN DATETIME,
	P_FECHAFIN IN DATETIME,
) 
AS
BEGIN
	--verificar que la fecha de inicio sea menor que la fecha de fin
	IF P_FECHAINICIO > P_FECHAFIN THEN
		raise_application_error(-15000,'{La fecha de inicio no puede ser mayor que la fecha de fin.}');
	ELSE
	SELECT COUNT(PRECIO) 'NUMERO_VENTAS', SUM(PRECIO) 'INGRESOS' FROM ventas_totales,
	(
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@hmo
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@quro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) ventas_totales
	ENDIF;
END VENTASPERIODOTIEMPO;
--------------------------------------------------------------------------------