--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, NUMERO_VENTAS, INGRESOS
	FROM
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA
		UNION
		SELECT 'HMO',COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@hmo
		UNION
		SELECT 'QRO', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@quro
		UNION
		SELECT 'TG', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@tg
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, NUMERO_VENTAS, INGRESOS
	FROM
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@mty
		UNION
		SELECT 'HMO',COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA
		UNION
		SELECT 'QRO', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@quro
		UNION
		SELECT 'TG', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@tg
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, NUMERO_VENTAS, INGRESOS
	FROM
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@mty
		UNION
		SELECT 'HMO',COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@hmo
		UNION
		SELECT 'QRO', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA
		UNION
		SELECT 'TG', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@tg
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, NUMERO_VENTAS, INGRESOS
	FROM
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@mty
		UNION
		SELECT 'HMO',COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@hmo
		UNION
		SELECT 'QRO', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA@quro
		UNION
		SELECT 'TG', COUNT(PRECIO) NUMERO_VENTAS ,SUM(PRECIO) INGRESOS
		FROM VENTA
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------