--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, TOTAL_VENTAS, INGRESOS
	FROM VENTAS_TOTALES,
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT 'HMO',COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@hmo
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'QRO', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@qro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'TG', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, TOTAL_VENTAS, INGRESOS
	FROM VENTAS_TOTALES,
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT 'HMO',COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'QRO', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@qro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'TG', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, TOTAL_VENTAS, INGRESOS
	FROM VENTAS_TOTALES,
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT 'HMO',COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@hmo
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'QRO', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'TG', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@tg
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE VIEW VENTASPORAGENCIA AS
(
	SELECT AGENCIA, TOTAL_VENTAS, INGRESOS
	FROM VENTAS_TOTALES,
	(
		SELECT 'MTY' AS AGENCIA, COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@mty
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		UNION
		SELECT 'HMO',COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@hmo
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'QRO', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA@qro
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
		SELECT 'TG', COUNT(PRECIO) 'NUMERO_VENTAS' ,SUM(PRECIO) 'INGRESOS'
		FROM VENTA
		WHERE FECHA BETWEEN P_FECHAINICIO AND P_FECHAFIN
	) VENTAS_TOTALES
)
--------------------------------------------------------------------------------