--mty
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX1 AS
	SELECT 'MTY' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA 
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX2 AS
	SELECT 'HMO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@hmo 
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX3 AS 
	SELECT 'QRO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX4 AS 
	SELECT 'TG' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@tg 
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
		WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDO AS
	SELECT * FROM VEHICULOMENORVENDIDOAUX1
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX2
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX3
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX4
----------------------------------------------------------------------------------------------------
--hmo
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX1 AS
	SELECT 'MTY' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@mty 
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX2 AS
	SELECT 'HMO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA 
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX3 AS 
	SELECT 'QRO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX4 AS 
	SELECT 'TG' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@tg 
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
		WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDO AS
	SELECT * FROM VEHICULOMENORVENDIDOAUX1
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX2
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX3
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX4
----------------------------------------------------------------------------------------------------
--qro
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX1 AS
	SELECT 'MTY' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@mty 
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX2 AS
	SELECT 'HMO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@hmo 
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX3 AS 
	SELECT 'QRO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX4 AS 
	SELECT 'TG' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@tg 
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
		WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDO AS
	SELECT * FROM VEHICULOMENORVENDIDOAUX1
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX2
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX3
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX4
----------------------------------------------------------------------------------------------------
--tg
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX1 AS
	SELECT 'MTY' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@mty 
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX2 AS
	SELECT 'HMO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@hmo 
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC

CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX3 AS 
	SELECT 'QRO' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
	WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDOAUX4 AS 
	SELECT 'TG' AS AGENCIA, CATALOGO.MODELO,  COUNT(CATALOGO.ID_CATALOGO) CANTIDAD FROM VENTA 
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	INNER JOIN CATALOGO ON INVENTARIO.ID_CATALOGO = CATALOGO.ID_CATALOGO
		WHERE ROWNUM=1
	GROUP BY (CATALOGO.MODELO)
	ORDER BY CANTIDAD ASC


CREATE OR REPLACE VIEW VEHICULOMENORVENDIDO AS
	SELECT * FROM VEHICULOMENORVENDIDOAUX1
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX2
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX3
	UNION
	SELECT * FROM VEHICULOMENORVENDIDOAUX4
----------------------------------------------------------------------------------------------------