--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX1 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX2 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@hmo
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX3 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX4 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@tg
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)


CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
    SELECT COLOR, CANTIDAD FROM
    (
        SELECT COLOR, SUM(CANTIDAD) CANTIDAD 
        FROM 
        (
            SELECT * FROM COLORMASDEMANDADOAUX1
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX2
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX3
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX4
        ) COLOR_INVENTARIOS 
        GROUP BY COLOR
        ORDER BY CANTIDAD DESC
    ) WHERE ROWNUM=1
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX1 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@mty
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX2 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX3 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX4 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@tg
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)


CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
    SELECT COLOR, CANTIDAD FROM
    (
        SELECT COLOR, SUM(CANTIDAD) CANTIDAD 
        FROM 
        (
            SELECT * FROM COLORMASDEMANDADOAUX1
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX2
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX3
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX4
        ) COLOR_INVENTARIOS 
        GROUP BY COLOR
        ORDER BY CANTIDAD DESC
    ) WHERE ROWNUM=1
--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX1 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@mty
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX2 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@hmo
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX3 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX4 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@tg
	INNER JOIN INVENTARIO@tg ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)


CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
    SELECT COLOR, CANTIDAD FROM
    (
        SELECT COLOR, SUM(CANTIDAD) CANTIDAD 
        FROM 
        (
            SELECT * FROM COLORMASDEMANDADOAUX1
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX2
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX3
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX4
        ) COLOR_INVENTARIOS 
        GROUP BY COLOR
        ORDER BY CANTIDAD DESC
    ) WHERE ROWNUM=1
--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX1 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@mty
	INNER JOIN INVENTARIO@mty ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX2 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@hmo
	INNER JOIN INVENTARIO@hmo ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX3 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA@quro
	INNER JOIN INVENTARIO@quro ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)

CREATE OR REPLACE VIEW COLORMASDEMANDADOAUX4 AS (
	SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTA
	INNER JOIN INVENTARIO ON VENTA.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
	GROUP BY INVENTARIO.COLOR
)


CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
    SELECT COLOR, CANTIDAD FROM
    (
        SELECT COLOR, SUM(CANTIDAD) CANTIDAD 
        FROM 
        (
            SELECT * FROM COLORMASDEMANDADOAUX1
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX2
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX3
            UNION
            SELECT * FROM COLORMASDEMANDADOAUX4
        ) COLOR_INVENTARIOS 
        GROUP BY COLOR
        ORDER BY CANTIDAD DESC
    ) WHERE ROWNUM=1
