--------------------------------------------------------------------------------
--MTY
CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
(
	SELECT TOP 1 COLOR, SUM(CANTIDAD) CANTIDAD 
	FROM COLOR_INVENTARIOS 
	GROUP BY COLOR
	ORDER BY CANTIDAD DESC
	,(
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS
		INNER JOIN INVENTARIO ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@hmo
		INNER JOIN INVENTARIO@hmo ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@quro
		INNER JOIN INVENTARIO@quro ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@tg
		INNER JOIN INVENTARIO@tg ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
	) COLOR_INVENTARIOS;
)
--------------------------------------------------------------------------------
--HMO
CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
(
	SELECT TOP 1 COLOR, SUM(CANTIDAD) CANTIDAD 
	FROM COLOR_INVENTARIOS 
	GROUP BY COLOR
	ORDER BY CANTIDAD DESC
	,(
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@mty
		INNER JOIN INVENTARIO@mty ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS
		INNER JOIN INVENTARIO ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@quro
		INNER JOIN INVENTARIO@quro ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@tg
		INNER JOIN INVENTARIO@tg ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
	) COLOR_INVENTARIOS;
)
--------------------------------------------------------------------------------
--QRO
CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
(
	SELECT TOP 1 COLOR, SUM(CANTIDAD) CANTIDAD 
	FROM COLOR_INVENTARIOS 
	GROUP BY COLOR
	ORDER BY CANTIDAD DESC
	,(
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@mty
		INNER JOIN INVENTARIO@mty ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@hmo
		INNER JOIN INVENTARIO@hmo ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS
		INNER JOIN INVENTARIO ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@tg
		INNER JOIN INVENTARIO@tg ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
	) COLOR_INVENTARIOS;
)
--------------------------------------------------------------------------------
--TG
CREATE OR REPLACE VIEW COLORMASDEMANDADO
AS
(
	SELECT TOP 1 COLOR, SUM(CANTIDAD) CANTIDAD 
	FROM COLOR_INVENTARIOS 
	GROUP BY COLOR
	ORDER BY CANTIDAD DESC
	,(
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@mty
		INNER JOIN INVENTARIO@mty ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@hmo
		INNER JOIN INVENTARIO@hmo ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		UNION
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS@quro
		INNER JOIN INVENTARIO@quro ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
		SELECT INVENTARIO.COLOR, COUNT(INVENTARIO.COLOR) CANTIDAD FROM VENTAS
		INNER JOIN INVENTARIO ON VENTAS.ID_INVENTARIO = INVENTARIO.ID_INVENTARIO
		GROUP BY INVENTARIO.COLOR
	) COLOR_INVENTARIOS;
)
