--mty
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR@ ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
)
--hmo
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
)
--qro
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
)
--tg
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
	UNION
	SELECT TOP 1 VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC
)