--mty
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDORAUX1 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.ID_VENDEDOR) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE,VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX2 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1


CREATE OR REPLACE VIEW MEJORVENDEDORAUX3 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX4 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1
	

CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
	SELECT * FROM MEJORVENDEDORAUX1
	UNION
	SELECT * FROM MEJORVENDEDORAUX2
	UNION
	SELECT * FROM MEJORVENDEDORAUX3
	UNION
	SELECT * FROM MEJORVENDEDORAUX4
)

--hmo
----------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MEJORVENDEDORAUX1 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.ID_VENDEDOR) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE,VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX2 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1


CREATE OR REPLACE VIEW MEJORVENDEDORAUX3 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX4 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1
	

CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
	SELECT * FROM MEJORVENDEDORAUX1
	UNION
	SELECT * FROM MEJORVENDEDORAUX2
	UNION
	SELECT * FROM MEJORVENDEDORAUX3
	UNION
	SELECT * FROM MEJORVENDEDORAUX4
)
--qro
----------------------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW MEJORVENDEDORAUX1 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.ID_VENDEDOR) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE,VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX2 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1


CREATE OR REPLACE VIEW MEJORVENDEDORAUX3 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX4 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@tg
	INNER JOIN VENDEDOR@tg ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1
	

CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
	SELECT * FROM MEJORVENDEDORAUX1
	UNION
	SELECT * FROM MEJORVENDEDORAUX2
	UNION
	SELECT * FROM MEJORVENDEDORAUX3
	UNION
	SELECT * FROM MEJORVENDEDORAUX4
)
--tg
----------------------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW MEJORVENDEDORAUX1 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.ID_VENDEDOR) VENTAS
	FROM VENTA@mty
	INNER JOIN VENDEDOR@mty ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE,VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX2 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@hmo
	INNER JOIN VENDEDOR@hmo ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1


CREATE OR REPLACE VIEW MEJORVENDEDORAUX3 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA@	quro
	INNER JOIN VENDEDOR@quro ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1

CREATE OR REPLACE VIEW MEJORVENDEDORAUX4 AS
	SELECT * FROM (SELECT VENDEDOR.NOMBRE, COUNT(VENDEDOR.NOMBRE) VENTAS
	FROM VENTA
	INNER JOIN VENDEDOR ON VENTA.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
	GROUP BY (VENDEDOR.NOMBRE, VENDEDOR.ID_VENDEDOR)
	ORDER BY VENTAS DESC)
	WHERE ROWNUM = 1
	

CREATE OR REPLACE VIEW MEJORVENDEDOR
AS
(
	SELECT * FROM MEJORVENDEDORAUX1
	UNION
	SELECT * FROM MEJORVENDEDORAUX2
	UNION
	SELECT * FROM MEJORVENDEDORAUX3
	UNION
	SELECT * FROM MEJORVENDEDORAUX4
)