--MTY
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX1 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX2 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX3 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX4 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOS
AS 
(	SELECT NOMBRE, NUMERO_UNIDADES FROM 
	(
		SELECT NOMBRE, SUM(NUMERO_UNIDADES) NUMERO_UNIDADES 
			FROM
			(
				SELECT * FROM MAYORNUMEROVEHICULOSAUX1
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX2
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX3
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX4
			)
        GROUP BY NOMBRE
        ORDER BY NUMERO_UNIDADES DESC
	) 
	WHERE ROWNUM=1
)

--HMO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX1 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX2 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX3 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX4 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOS
AS 
(	SELECT NOMBRE, NUMERO_UNIDADES FROM 
	(
		SELECT NOMBRE, SUM(NUMERO_UNIDADES) NUMERO_UNIDADES 
			FROM
			(
				SELECT * FROM MAYORNUMEROVEHICULOSAUX1
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX2
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX3
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX4
			)
        GROUP BY NOMBRE
        ORDER BY NUMERO_UNIDADES DESC
	) 
	WHERE ROWNUM=1
)
--QRO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX1 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX2 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX3 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX4 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOS
AS 
(	SELECT NOMBRE, NUMERO_UNIDADES FROM 
	(
		SELECT NOMBRE, SUM(NUMERO_UNIDADES) NUMERO_UNIDADES 
			FROM
			(
				SELECT * FROM MAYORNUMEROVEHICULOSAUX1
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX2
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX3
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX4
			)
        GROUP BY NOMBRE
        ORDER BY NUMERO_UNIDADES DESC
	) 
	WHERE ROWNUM=1
)

--TG
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX1 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX2 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX3 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOSAUX4 AS
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ENSAMBLADORA.ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)
		
CREATE OR REPLACE VIEW MAYORNUMEROVEHICULOS
AS 
(	SELECT NOMBRE, NUMERO_UNIDADES FROM 
	(
		SELECT NOMBRE, SUM(NUMERO_UNIDADES) NUMERO_UNIDADES 
			FROM
			(
				SELECT * FROM MAYORNUMEROVEHICULOSAUX1
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX2
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX3
				UNION
				SELECT * FROM MAYORNUMEROVEHICULOSAUX4
			)
        GROUP BY NOMBRE
        ORDER BY NUMERO_UNIDADES DESC
	) 
	WHERE ROWNUM=1
)