--MTY
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORA MAYORNUMEROVEHICULOS
AS 
(
	SELECT TOP 1 NOMBRE, COUNT(NUMERO_UNIDADES) NUMERO_UNIDADES 
	FROM
	(
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
	) 
	GROUP BY NOMBRE;
)
--HMO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORA MAYORNUMEROVEHICULOS
AS 
(
	SELECT NOMBRE, COUNT(NUMERO_UNIDADES) NUMERO_UNIDADES 
	FROM
	(
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
	) 
	GROUP BY NOMBRE;
)
--QRO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORA MAYORNUMEROVEHICULOS
AS 
(
	SELECT NOMBRE, COUNT(NUMERO_UNIDADES) NUMERO_UNIDADES 
	FROM
	(
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@tg
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
	) 
	GROUP BY NOMBRE;
)
--TG
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORA MAYORNUMEROVEHICULOS
AS 
(
	SELECT NOMBRE, COUNT(NUMERO_UNIDADES) NUMERO_UNIDADES 
	FROM
	(
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@mty
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		GROUP BY ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@quro
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO@hmo
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
		UNION
		SELECT ENSAMBLADORA.NOMBRE, COUNT(ID_ENSAMBLADORA) NUMERO_UNIDADES FROM INVENTARIO
		INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
	) 
	GROUP BY NOMBRE;
)