--MTY
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX1 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO) DEFECTOS
    INNER JOIN INVENTARIO ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX2 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
    FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@hmo) DEFECTOS
    INNER JOIN INVENTARIO@hmo ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX3 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@quro) DEFECTOS
    INNER JOIN INVENTARIO@quro ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX4 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@tg) DEFECTOS
    INNER JOIN INVENTARIO@tg ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOS 
AS
(	SELECT * FROM 
    (
        SELECT NOMBRE, SUM(UNIDADES_DEFECTUOSAS) UNIDADES_DEFECTUOSAS
        FROM
        (
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX1
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX2
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX3
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX4
        )
        GROUP BY(NOMBRE)
    )
    WHERE ROWNUM=1
)
--HMO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX1 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@mty) DEFECTOS
    INNER JOIN INVENTARIO@mty ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX2 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
    FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO) DEFECTOS
    INNER JOIN INVENTARIO ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX3 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@quro) DEFECTOS
    INNER JOIN INVENTARIO@quro ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX4 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@tg) DEFECTOS
    INNER JOIN INVENTARIO@tg ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOS 
AS
(	SELECT * FROM 
    (
        SELECT NOMBRE, SUM(UNIDADES_DEFECTUOSAS) UNIDADES_DEFECTUOSAS
        FROM
        (
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX1
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX2
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX3
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX4
        )
        GROUP BY(NOMBRE)
    )
    WHERE ROWNUM=1
)
--QRO
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX1 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@mty) DEFECTOS
    INNER JOIN INVENTARIO@mty ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX2 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
    FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@hmo) DEFECTOS
    INNER JOIN INVENTARIO@hmo ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX3 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO) DEFECTOS
    INNER JOIN INVENTARIO ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX4 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@tg) DEFECTOS
    INNER JOIN INVENTARIO@tg ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOS 
AS
(	SELECT * FROM 
    (
        SELECT NOMBRE, SUM(UNIDADES_DEFECTUOSAS) UNIDADES_DEFECTUOSAS
        FROM
        (
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX1
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX2
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX3
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX4
        )
        GROUP BY(NOMBRE)
    )
    WHERE ROWNUM=1
)
--TG
---------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX1 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@mty) DEFECTOS
    INNER JOIN INVENTARIO@mty ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX2 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
    FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@hmo) DEFECTOS
    INNER JOIN INVENTARIO@hmo ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX3 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO@quro) DEFECTOS
    INNER JOIN INVENTARIO@quro ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOSAUX4 AS
    SELECT ENSAMBLADORA.NOMBRE, COUNT(INVENTARIO.ID_ENSAMBLADORA) UNIDADES_DEFECTUOSAS
	FROM (SELECT DISTINCT ID_INVENTARIO FROM INVENTARIO_DEFECTO) DEFECTOS
    INNER JOIN INVENTARIO ON INVENTARIO.ID_INVENTARIO = DEFECTOS.ID_INVENTARIO
    INNER JOIN ENSAMBLADORA ON INVENTARIO.ID_ENSAMBLADORA = ENSAMBLADORA.ID_ENSAMBLADORA
    GROUP BY (ENSAMBLADORA.NOMBRE,ENSAMBLADORA.ID_ENSAMBLADORA)

CREATE OR REPLACE VIEW ENSAMBLADORAMAYORDEFECTOS 
AS
(	SELECT * FROM 
    (
        SELECT NOMBRE, SUM(UNIDADES_DEFECTUOSAS) UNIDADES_DEFECTUOSAS
        FROM
        (
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX1
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX2
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX3
            UNION
            SELECT * FROM ENSAMBLADORAMAYORDEFECTOSAUX4
        )
        GROUP BY(NOMBRE)
    )
    WHERE ROWNUM=1
)