DROP TABLE VENTA;
DROP TABLE INVENTARIO_DEFECTO;
DROP TABLE INVENTARIO;
DROP TABLE VENDEDOR;
DROP TABLE DEFECTO;
DROP TABLE ENSAMBLADORA;
DROP TABLE CATALOGO;

CREATE TABLE CATALOGO
(
    ID_CATALOGO NUMBER(10) NOT NULL, 
    MODELO VARCHAR2(50) NOT NULL, 
    ANO CHAR(4) NOT NULL
);
  
CREATE TABLE DEFECTO
(	
    ID_TIPO_DEFECTO NUMBER(10) NOT NULL, 
    DESCRIPCION VARCHAR2(300) NOT NULL
);
  
CREATE TABLE ENSAMBLADORA
(
    ID_ENSAMBLADORA NUMBER(10) NOT NULL, 
    NOMBRE VARCHAR2(200) NOT NULL, 
    DIRECCION VARCHAR2(300) NOT NULL, 
    TELEFONO VARCHAR2(20) NOT NULL
);
  
CREATE TABLE INVENTARIO    
(	
    ID_INVENTARIO NUMBER(10) NOT NULL, 
    COLOR VARCHAR2(20) NOT NULL, 
    TIPO VARCHAR2(40) NOT NULL, 
    PRECIO_LISTA NUMBER(10,2) NOT NULL, 
    STATUS VARCHAR2(30) NOT NULL, 
    ID_ENSAMBLADORA NUMBER(10) NOT NULL, 
    ID_CATALOGO NUMBER(10) NOT NULL, 
    ID_AGENCIA NUMBER(10) NOT NULL
);

CREATE TABLE INVENTARIO_DEFECTO    
(	
    ID_TIPO_DEFECTO NUMBER(10) NOT NULL, 
    ID_INVENTARIO NUMBER(10) NOT NULL, 
    FECHA_INGRESO DATE NOT NULL, 
    FECHA_ENTREGA DATE NOT NULL, 
    ID_AGENCIA NUMBER(10) NOT NULL   
);

CREATE TABLE VENDEDOR 
(	
    ID_VENDEDOR NUMBER NOT NULL, 
    NOMBRE VARCHAR2(40) NOT NULL, 
    EDAD NUMBER NOT NULL, 
    SEXO VARCHAR2(20) NOT NULL, 
    TELEFONO VARCHAR2(20) NOT NULL, 
    CORREO VARCHAR2(40) NOT NULL, 
    STATUS NUMBER NOT NULL, 
    ID_AGENCIA NUMBER NOT NULL
);
  
CREATE TABLE VENTA
(	
    ID_INVENTARIO NUMBER(10) NOT NULL, 
    ID_VENDEDOR NUMBER(10) NOT NULL, 
    FECHA DATE NOT NULL, 
    PRECIO NUMBER(10,2) NOT NULL,
    COMISION NUMBER(10,2) NOT NULL, 
    ID_AGENCIA NUMBER(10) NOT NULL   
);

CREATE UNIQUE INDEX CATALOGO_PK ON CATALOGO (ID_CATALOGO);

ALTER TABLE CATALOGO ADD (CONSTRAINT CATALOGO_PK PRIMARY KEY (ID_CATALOGO)
  USING INDEX CATALOGO_PK ENABLE VALIDATE);
  
CREATE UNIQUE INDEX DEFECTO_PK ON DEFECTO (ID_TIPO_DEFECTO);

ALTER TABLE DEFECTO ADD (CONSTRAINT DEFECTO_PK PRIMARY KEY (ID_TIPO_DEFECTO)
  USING INDEX DEFECTO_PK ENABLE VALIDATE);  
  
CREATE UNIQUE INDEX ENSAMBLADORA_PK ON ENSAMBLADORA (ID_ENSAMBLADORA);

ALTER TABLE ENSAMBLADORA ADD (CONSTRAINT ENSAMBLADORA_PK PRIMARY KEY (ID_ENSAMBLADORA)
  USING INDEX ENSAMBLADORA_PK ENABLE VALIDATE);  
  
CREATE UNIQUE INDEX INVENTARIO_PK ON INVENTARIO (ID_INVENTARIO);

ALTER TABLE INVENTARIO ADD (CONSTRAINT INVENTARIO_PK PRIMARY KEY (ID_INVENTARIO)
  USING INDEX INVENTARIO_PK ENABLE VALIDATE);

ALTER TABLE INVENTARIO ADD (CONSTRAINT INVENTARIO_FK1
  FOREIGN KEY (ID_ENSAMBLADORA) REFERENCES ENSAMBLADORA (ID_ENSAMBLADORA) ENABLE VALIDATE);

ALTER TABLE INVENTARIO ADD (CONSTRAINT INVENTARIO_FK2
  FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO (ID_CATALOGO) ENABLE VALIDATE);
  
ALTER TABLE INVENTARIO_DEFECTO ADD (CONSTRAINT INVENTARIO_DEFECTO_FK1
  FOREIGN KEY (ID_TIPO_DEFECTO) REFERENCES DEFECTO (ID_TIPO_DEFECTO) ENABLE VALIDATE);

ALTER TABLE INVENTARIO_DEFECTO ADD (CONSTRAINT INVENTARIO_DEFECTO_FK2
  FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO) ENABLE VALIDATE);  
  
CREATE UNIQUE INDEX VENDEDOR_PK ON VENDEDOR (ID_VENDEDOR);

ALTER TABLE VENDEDOR ADD (CONSTRAINT VENDEDOR_PK PRIMARY KEY (ID_VENDEDOR)
  USING INDEX VENDEDOR_PK ENABLE VALIDATE);  
  
ALTER TABLE VENTA ADD (CONSTRAINT VENTA_FK1
  FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO) ENABLE VALIDATE);

ALTER TABLE VENTA ADD (CONSTRAINT VENTA_FK2
  FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR) ENABLE VALIDATE);

