-- QURO
---------------------------------------
CREATE OR REPLACE PROCEDURE MOVERVENDEDOR
(
	P_AGENCIA_DESTINO IN VARCHAR2,
	P_ID_VENDEDOR IN NUMBER
)
AS
V_EXISTE_VENDEDOR NUMBER;
V_STATUS_VENDEDOR VARCHAR2(100);
BEGIN
  SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
	IF V_EXISTE_VENDEDOR = 0 THEN
    raise_application_error(-20000,'{el vendedor no existe}');
  ELSE
    SELECT STATUS INTO V_STATUS_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
    IF V_STATUS_VENDEDOR = 1 THEN
      IF P_AGENCIA_DESTINO = 'MTY' THEN
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@MTY WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@MTY SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@MTY (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF;
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'HMO' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@HMO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@HMO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@HMO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR;  
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'TG' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@TG WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@TG SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@TG (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      END IF;
    ELSE 
      raise_application_error(-20001,'{El vendedor no se encuentra en esta agencia}');
    END IF;
  END IF;
END MOVERVENDEDOR;
/
---------------------------------------

-- TG
---------------------------------------
CREATE OR REPLACE PROCEDURE MOVERVENDEDOR
(
	P_AGENCIA_DESTINO IN VARCHAR2,
	P_ID_VENDEDOR IN NUMBER
)
AS
V_EXISTE_VENDEDOR NUMBER;
V_STATUS_VENDEDOR VARCHAR2(100);
BEGIN
  SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
	IF V_EXISTE_VENDEDOR = 0 THEN
    raise_application_error(-20000,'{el vendedor no existe}');
  ELSE
    SELECT STATUS INTO V_STATUS_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
    IF V_STATUS_VENDEDOR = 1 THEN
      IF P_AGENCIA_DESTINO = 'MTY' THEN
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@MTY WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@MTY SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@MTY (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF;
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'HMO' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@HMO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@HMO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@HMO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR;  
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'QURO' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@QURO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@QURO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@QURO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      END IF;
    ELSE 
      raise_application_error(-20001,'{El vendedor no se encuentra en esta agencia}');
    END IF;
  END IF;
END MOVERVENDEDOR;
/
---------------------------------------

-- MTY
---------------------------------------
CREATE OR REPLACE PROCEDURE MOVERVENDEDOR
(
	P_AGENCIA_DESTINO IN VARCHAR2,
	P_ID_VENDEDOR IN NUMBER
)
AS
V_EXISTE_VENDEDOR NUMBER;
V_STATUS_VENDEDOR VARCHAR2(100);
BEGIN
  SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
	IF V_EXISTE_VENDEDOR = 0 THEN
    raise_application_error(-20000,'{el vendedor no existe}');
  ELSE
    SELECT STATUS INTO V_STATUS_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
    IF V_STATUS_VENDEDOR = 1 THEN
      IF P_AGENCIA_DESTINO = 'QURO' THEN
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@QURO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@QURO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@QURO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF;
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'HMO' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@HMO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@HMO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@HMO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR;  
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'TG' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@TG WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@TG SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@TG (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      END IF;
    ELSE 
      raise_application_error(-20001,'{El vendedor no se encuentra en esta agencia}');
    END IF;
  END IF;
END MOVERVENDEDOR;
/
---------------------------------------

-- HMO
---------------------------------------
CREATE OR REPLACE PROCEDURE MOVERVENDEDOR
(
	P_AGENCIA_DESTINO IN VARCHAR2,
	P_ID_VENDEDOR IN NUMBER
)
AS
V_EXISTE_VENDEDOR NUMBER;
V_STATUS_VENDEDOR VARCHAR2(100);
BEGIN
  SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
	IF V_EXISTE_VENDEDOR = 0 THEN
    raise_application_error(-20000,'{el vendedor no existe}');
  ELSE
    SELECT STATUS INTO V_STATUS_VENDEDOR FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR;
    IF V_STATUS_VENDEDOR = 1 THEN
      IF P_AGENCIA_DESTINO = 'MTY' THEN
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@MTY WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@MTY SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@MTY (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF;
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'QURO' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@QURO WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@QURO SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@QURO (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR;  
        COMMIT;
      ELSIF P_AGENCIA_DESTINO = 'TG' THEN 
        SELECT COUNT(1) INTO V_EXISTE_VENDEDOR FROM VENDEDOR@TG WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        IF V_EXISTE_VENDEDOR = 1 THEN
          UPDATE VENDEDOR@TG SET STATUS=1 WHERE ID_VENDEDOR = P_ID_VENDEDOR;
        ELSE
          INSERT INTO VENDEDOR@TG (SELECT * FROM VENDEDOR WHERE ID_VENDEDOR = P_ID_VENDEDOR); 
        END IF; 
        UPDATE VENDEDOR SET STATUS=0 WHERE ID_VENDEDOR = P_ID_VENDEDOR; 
        COMMIT;
      END IF;
    ELSE 
      raise_application_error(-20001,'{El vendedor no se encuentra en esta agencia}');
    END IF;
  END IF;
END MOVERVENDEDOR;
/
---------------------------------------