-- QURO
---------------------------------------
CREATE OR REPLACE PROCEDURE SUBIRPRECIO
(
	P_INFLACION IN NUMBER
)
AS
BEGIN
  UPDATE INVENTARIO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@MTY SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@HMO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@TG SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta';
  COMMIT;
END SUBIRPRECIO;
/
---------------------------------------

-- TG
---------------------------------------
CREATE OR REPLACE PROCEDURE SUBIRPRECIO
(
	P_INFLACION IN NUMBER
)
AS
BEGIN
  UPDATE INVENTARIO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@MTY SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@HMO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@QURO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta';
  COMMIT;
END SUBIRPRECIO;
/
---------------------------------------

-- MTY
---------------------------------------
CREATE OR REPLACE PROCEDURE SUBIRPRECIO
(
	P_INFLACION IN NUMBER
)
AS
BEGIN
  UPDATE INVENTARIO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@QURO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@HMO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@TG SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta';
  COMMIT;
END SUBIRPRECIO;
/
---------------------------------------

-- HMO
---------------------------------------
CREATE OR REPLACE PROCEDURE SUBIRPRECIO
(
	P_INFLACION IN NUMBER
)
AS
BEGIN
  UPDATE INVENTARIO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@MTY SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@QURO SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta'; 
  UPDATE INVENTARIO@TG SET PRECIO_LISTA = PRECIO_LISTA + (PRECIO_LISTA * P_INFLACION) WHERE STATUS = 'en venta';
  COMMIT;
END SUBIRPRECIO;
/
---------------------------------------