-- MTY
---------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARDEFECTO
(
	P_DESCRIPCION IN VARCHAR2
)
AS
    V_ID_TIPO_DEFECTO NUMBER;
BEGIN
    SELECT MAX(ID_TIPO_DEFECTO) INTO V_ID_TIPO_DEFECTO FROM DEFECTO;
    
    INSERT INTO DEFECTO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@HMO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@QURO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@TG (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    COMMIT;
END REGISTRARDEFECTO;
/
---------------------------------------

-- HMO
---------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARDEFECTO
(
	P_DESCRIPCION IN VARCHAR2
)
AS
    V_ID_TIPO_DEFECTO NUMBER;
BEGIN
    SELECT MAX(ID_TIPO_DEFECTO) INTO V_ID_TIPO_DEFECTO FROM DEFECTO;
    
    INSERT INTO DEFECTO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@MTY (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@QURO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@TG (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    COMMIT;
END REGISTRARDEFECTO;
/
---------------------------------------

-- QURO
---------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARDEFECTO
(
	P_DESCRIPCION IN VARCHAR2
)
AS
    V_ID_TIPO_DEFECTO NUMBER;
BEGIN
    SELECT MAX(ID_TIPO_DEFECTO) INTO V_ID_TIPO_DEFECTO FROM DEFECTO;
    
    INSERT INTO DEFECTO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@HMO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@MTY (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@TG (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    COMMIT;
END REGISTRARDEFECTO;
/
---------------------------------------

-- TG
---------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARDEFECTO
(
	P_DESCRIPCION IN VARCHAR2
)
AS
    V_ID_TIPO_DEFECTO NUMBER;
BEGIN
    SELECT MAX(ID_TIPO_DEFECTO) INTO V_ID_TIPO_DEFECTO FROM DEFECTO;
    
    INSERT INTO DEFECTO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@HMO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@QURO (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    INSERT INTO DEFECTO@MTY (ID_TIPO_DEFECTO, DESCRIPCION) VALUES(V_ID_TIPO_DEFECTO+1, P_DESCRIPCION);
    COMMIT;
END REGISTRARDEFECTO;
/
