-- MTY      
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARDEFECTO
(
    P_ID_TIPO_DEFECTO IN NUMBER,
	P_DESCRIPCION IN VARCHAR2
)
AS
BEGIN   
    UPDATE DEFECTO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@HMO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@QURO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@TG SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    COMMIT;
END EDITARDEFECTO;
/
---------------------------------------

-- HMO
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARDEFECTO
(
    P_ID_TIPO_DEFECTO IN NUMBER,
	P_DESCRIPCION IN VARCHAR2
)
AS
BEGIN    
    UPDATE DEFECTO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@MTY SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@QURO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@TG SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    COMMIT;
END EDITARDEFECTO;
/
---------------------------------------

-- QURO
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARDEFECTO
(
    P_ID_TIPO_DEFECTO IN NUMBER,
	P_DESCRIPCION IN VARCHAR2
)
AS
BEGIN    
    UPDATE DEFECTO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@HMO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@MTY SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@TG SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    COMMIT;
END EDITARDEFECTO;
/
---------------------------------------

-- TG
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARDEFECTO
(
    P_ID_TIPO_DEFECTO IN NUMBER,
	P_DESCRIPCION IN VARCHAR2
)
AS
BEGIN    
    UPDATE DEFECTO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@HMO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@QURO SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    UPDATE DEFECTO@MTY SET DESCRIPCION = P_DESCRIPCION WHERE ID_TIPO_DEFECTO = P_ID_TIPO_DEFECTO;
    COMMIT;
END EDITARDEFECTO;
/


