-- MTY    
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARCATALOGO
(
    P_ID_CATALOGO IN NUMBER,
    P_MODELO IN VARCHAR2,
	P_ANO IN VARCHAR2
)
AS
BEGIN    
    UPDATE CATALOGO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@HMO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@QURO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@TG SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    COMMIT;
END EDITARCATALOGO;
/
---------------------------------------

-- HMO
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARCATALOGO
(
    P_ID_CATALOGO IN NUMBER,
    P_MODELO IN VARCHAR2,
	P_ANO IN VARCHAR2
)
AS
BEGIN    
    UPDATE CATALOGO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@MTY SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@QURO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@TG SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    COMMIT;
END EDITARCATALOGO;
/
---------------------------------------

-- QURO
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARCATALOGO
(
    P_ID_CATALOGO IN NUMBER,
    P_MODELO IN VARCHAR2,
	P_ANO IN VARCHAR2
)
AS
BEGIN    
    UPDATE CATALOGO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@HMO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@MTY SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@TG SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    COMMIT;
END EDITARCATALOGO;
/
---------------------------------------

-- TG
---------------------------------------
CREATE OR REPLACE PROCEDURE EDITARCATALOGO
(
    P_ID_CATALOGO IN NUMBER,
    P_MODELO IN VARCHAR2,
	P_ANO IN VARCHAR2
)
AS
BEGIN    
    UPDATE CATALOGO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@HMO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@QURO SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    UPDATE CATALOGO@MTY SET MODELO = P_MODELO, ANO = P_ANO WHERE ID_CATALOGO = P_ID_CATALOGO;
    COMMIT;
END EDITARCATALOGO;
/


