---MTY
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@qro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---HMO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	INSERT INTO ID_ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@qro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---QRO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	INSERT INTO ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---TG
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	INSERT INTO ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@qro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(/*sequencia*/, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/