---MTY
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
  V_ID_ENSAMBLADORA NUMBER;
BEGIN
  SELECT MAX(ID_ENSAMBLADORA) INTO V_ID_ENSAMBLADORA FROM ENSAMBLADORA;
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@qro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---HMO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
  V_ID_ENSAMBLADORA NUMBER;
BEGIN
  SELECT MAX(ID_ENSAMBLADORA) INTO V_ID_ENSAMBLADORA FROM ENSAMBLADORA;
	INSERT INTO ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@quro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---QRO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
  V_ID_ENSAMBLADORA NUMBER;
BEGIN
  SELECT MAX(ID_ENSAMBLADORA) INTO V_ID_ENSAMBLADORA FROM ENSAMBLADORA;
	INSERT INTO ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@tg(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---TG
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE REGISTRARENSAMBLADORA
(
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
  V_ID_ENSAMBLADORA NUMBER;
BEGIN
  SELECT MAX(ID_ENSAMBLADORA) INTO V_ID_ENSAMBLADORA FROM ENSAMBLADORA;
	INSERT INTO ENSAMBLADORA@mty(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@hmo(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA@quro(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	INSERT INTO ENSAMBLADORA(ID_ENSAMBLADORA, NOMBRE,DIRECCION,TELEFONO) VALUES(V_ID_ENSAMBLADORA+1, P_NOMBREENSAMBLADORA,P_DIRECCIONENSAMBLADORA,P_TELEFONOENSAMBLADORA);
	COMMIT;
END REGISTRARENSAMBLADORA;
/