---MTY
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@qro SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---HMO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@qro SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---QRO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END REGISTRARENSAMBLADORA;
/
---TG
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR(200),
	P_DIRECCIONENSAMBLADORA IN VARCHAR(300),
	P_TELEFONOENSAMBLADORA IN VARCHAR(20)
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@qro SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBRENESAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END REGISTRARENSAMBLADORA;
/
