---MTY
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
BEGIN
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@quro SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END EDITARENSAMBLADORA;
/
---HMO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@quro SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END EDITARENSAMBLADORA;
/
---QRO
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@tg SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END EDITARENSAMBLADORA;
/
---TG
----------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE EDITARENSAMBLADORA
(
	P_IDENSAMBLADORA IN NUMBER,
	P_NOMBREENSAMBLADORA IN VARCHAR,
	P_DIRECCIONENSAMBLADORA IN VARCHAR,
	P_TELEFONOENSAMBLADORA IN VARCHAR
)
AS
BEGIN
	UPDATE ENSAMBLADORA@mty SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@hmo SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA@quro SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	UPDATE ENSAMBLADORA SET NOMBRE = P_NOMBREENSAMBLADORA, DIRECCION = P_DIRECCIONENSAMBLADORA, TELEFONO = P_TELEFONOENSAMBLADORA WHERE ID_ENSAMBLADORA = P_IDENSAMBLADORA;
	COMMIT;
END EDITARENSAMBLADORA;
/

COMMIT;
